package com.example.feedme.models;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.util.HashMap;
import java.util.Map;

@Entity
public class Recipe {
    // recipe id auto-generated by firebase
//  String recipeId;
    @PrimaryKey
    @NonNull
    String userId = "";
    String recipeImage;
    String recipeTitle = "";
    String recipeBody = "";

    static final String TITLE = "title";
    static final String USERID = "userId";
    static final String IMAGE = "image";
    static final String BODY = "body";
    static final String COLLECTION = "recipes";
    static final String LAST_UPDATED = "lastUpdated";
    static final String LOCAL_LAST_UPDATED = "recipes_local_last_updated";


    public Recipe(String userId, String recipeImage, String recipeTitle, String recipeBody) {
        this.userId = userId;
        this.recipeImage = recipeImage;
        this.recipeTitle = recipeTitle;
        this.recipeBody = recipeBody;
    }

    public static Long getLocalLastUpdate() {
        //TODO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        return null;
    }
    public String getUserId(){ return userId; }

    public String getRecipeImage() {
        return recipeImage;
    }

    public String getRecipeTitle() {
        return recipeTitle;
    }

    public String getRecipeBody() {
        return recipeBody;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public void setRecipeImage(String recipeImage) {
        this.recipeImage = recipeImage;
    }

    public void setRecipeTitle(String recipeTitle) {
        this.recipeTitle = recipeTitle;
    }

    public void setRecipeBody(String recipeBody) {
        this.recipeBody = recipeBody;
    }

    public static Recipe fromJson(Map<String, Object> json){
        String userId = (String)json.get(USERID);
        String title = (String) json.get(TITLE);
        String body = (String) json.get(BODY);
        String image = (String) json.get(IMAGE);

        Recipe recipe = new Recipe(userId,image, title, body);

        return recipe;
    }

    public Map<String, Object> toJson(){
        Map<String, Object> json = new HashMap<>();

        json.put(USERID, getUserId());
        json.put(TITLE, getRecipeTitle());
        json.put(BODY, getRecipeBody());
        json.put(IMAGE, getRecipeImage());

        return json;
    }


}
